CONFIG_SERIAL=n
CONFIG_UART_CONSOLE=n
CONFIG_GPIO=y
CONFIG_NRFX_UARTE=y
CONFIG_MAIN_STACK_SIZE=4096

# nRF54: no periodic sys tick during long WFE gaps; wake on next timer event only.
CONFIG_TICKLESS_KERNEL=y
